version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rex000777
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgres://appuser:strongpassword@db:5432/appdb
      # Add other env vars as needed
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
#    env_file:
#      - src/.env
    environment:
      NODE_ENV: production
    networks:
      - appnet

  proxy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  appnet:
    driver: bridge